apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: wazuh
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  privileged: true # SUBJECT TO OMITTED, ask TDR later.
  template:
    metadata:
      labels:
        app: wazuh-agent
      name: wazuh-agent
    spec:
      hostPID: true
      hostIPC: true
      containers:
        - name: wazuh-agent
          image: 'hbcwl/wazuh-agent:3.10.2-0.0.4'
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
          volumeMounts:
            # Mount a volume for docker script running
            # since the path under rootpath in COS is not runable
            - name: wazuh-agent
              mountPath: /entrypoint-scripts
      volumes:
      - name: wazuh-agent
        persistentVolumeClaim: 
          claimName: wazuh-agent
