apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-agent
  namespace: wazuh
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: gce-pd-encrypted-retained #defined in Wazuh-kubernetes
  # selector:
  #   matchLabels:
  #     release: "stable"
  #   matchExpressions:
  #     - {key: environment, operator: In, values: [dev]}