apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: wazuh
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  template:
    metadata:
      labels:
        app: wazuh-agent
      name: wazuh-agent
    spec:
      hostPID: true
      hostIPC: true
      volumes:
      - name: wazuh-agent
        persistentVolumeClaim: 
          claimName: wazuh-agent
      - name: wazuh-agent-conf-volume
        configMap: 
          name: wazuh-agent-conf
      - name: host-os-release
        hostPath:
          path: /etc/os-release
      containers:
        - name: wazuh-agent
          image: 'hbcwl/wazuh-agent:3.10.2-0.0.6'
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
          volumeMounts:
            # Mount a volume for docker script running
            # since the path under rootpath in COS is not runable
            - name: wazuh-agent
              mountPath: /entrypoint-scripts
            - name: wazuh-agent-conf-volume
              mountPath: /var/ossec/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true
            - name: host-os-release
              mountPath: /etc/os-release
              readOnly: true
