apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-agent
  namespace: wazuh
spec:
  storageClassName: gce-pd-encrypted-retained
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/var/wazuh-agent"